server:
  port: 8888
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wanke?useUnicode=true&prepStmtCacheSize=517&cachePrepStmts=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: ff871125
      filters: stat,slf4j
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    # 配置 DBMS 类型
    database: MYSQL
    # 配置是否将执行的 SQL 输出到日志
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis: 
    database: 0
    host: 172.16.10.51
    port: 16379
    password: 
    timeout: 0
    pool: 
      max-active: 1000
      max-wait: -1
      max-idle: 10
      min-idle: 0
    expireTime: 7200
logging: 
  config: classpath:log4j2-dev.xml