spring:
  profiles: 
    active: dev
  session: 
    store-type: none
  jackson: 
    serialization: 
      indent_output: true
#jwt:
#  header: Authorization
#  secret: wanke-secret2018
#  expiration: 604800 #token七天不过期
#  tokenHead: "Bearer "
#  exceptUrl: "/auth/**"