server:
  port: 8888
spring:
  datasource:
    druid:
      url: jdbc:mysql://mysql:3306/wanke?useUnicode=true&characterEncoding=utf8
      username: root
      password: ff871125
      filters: stat,slf4j
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  redis: 
    database: 0
    host: redis
    port: 6379
    password: 
    timeout: 0
    pool: 
      max-active: 10
      max-wait: -1
      max-idle: 10
      min-idle: 0
    expireTime: 7200
logging: 
  config: classpath:log4j2-prod.xml